services:
  - type: web
    name: game-api
    runtime: python
    repo: https://github.com/zAtaoo/game-site
    plan: free
    region: singapore
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: bash start.sh
    healthCheckPath: /api/games
